Repository FaridSafi/react-native-google-places-autocomplete, pull requests merged in 2020-05, with the labels that each got.

#403 Add TypeScript definitions (.d.ts) file
  GooglePlacesAutocomplete.d.ts
Labels: enhancement

#530 fix(props.text) pass proper callback to setState
  GooglePlacesAutocomplete.js
Labels: awaiting author response

#398 Ensure list view doesn't show unexpectedly
  GooglePlacesAutocomplete.js
Labels: bug
